#!/usr/bin/env python
# -*- coding: latin-1 -*- ######################################################
#                                                                              #
# blackarch-installer - Installer for BlackArch Linux                          #
#                                                                              #
# FILE                                                                         #
# blackarch-installer.py                                                       #
#                                                                              #
# DATE                                                                         #
# 2015-02-17                                                                   #
#                                                                              #
# AUTHOR                                                                       #
# Levon 'noptrix' Kayan - <noptrix@nullsecurity.net>                           #
#                                                                              #
################################################################################


# own imports
from core.controller import Controller
from core.wrapper import Wrapper

# sys imports
import sys


if __name__ == "__main__":
    try:
        c = Controller()
        c.start()
        c.end()
    except KeyboardInterrupt:
        sys.stdout.flush()
        sys.stdout.write('\b\b')
        sys.stdout.write('\n')
        Wrapper.warn('aborted by user')
        raise SystemExit


# EOF
